"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import PingIcon from "@/components/PingIcon";
import { CATEGORY_DEFINITIONS, CATEGORY_ORDER, type PingCategoryKey, type Radius } from "@/lib/ping-categories";
import { readPingRadius, writePingRadius } from "@/lib/ping-local-preferences";
import { getPingLocationSilently, requestPingLocation, type PingCoordinates, type PingLocationState } from "@/lib/ping-location";

type CategoryKey = "all" | PingCategoryKey;
type SortKey = "best" | "newest" | "closest" | "confirmed";
type SearchRow = { id:string; user_id:string; category:PingCategoryKey; title:string; body:string; place_label:string|null; confirmation_count:number; comment_count:number; created_at:string; expires_at:string; distance_meters:number; search_rank:number; };
type SearchItem = SearchRow & { mediaUrl?:string; lastConfirmedAt?:string|null };
type PingMediaRow = { ping_id:string; storage_path:string };
type MetaRow = { id:string; last_confirmed_at:string|null };

function ageLabel(value:string){const m=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(m<1)return"just now";if(m<60)return`${m}m ago`;const h=Math.floor(m/60);return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`;}
function confirmLabel(value?:string|null){if(!value)return"";const m=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(m<1)return"just now";if(m<60)return`${m}m ago`;const h=Math.floor(m/60);return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`;}

async function enrich(rows:SearchRow[]){if(!rows.length)return rows as SearchItem[];const supabase=createClient();const ids=rows.map(r=>r.id);const[media,meta]=await Promise.all([supabase.from("ping_media").select("ping_id,storage_path").in("ping_id",ids),supabase.from("pings").select("id,last_confirmed_at").in("id",ids)]);const urls=new Map<string,string>();if(!media.error&&media.data?.length){const mediaRows=media.data as PingMediaRow[];const signed=await supabase.storage.from("ping-media").createSignedUrls(mediaRows.map(r=>r.storage_path),900);if(!signed.error&&signed.data)mediaRows.forEach((r,i)=>{const url=signed.data?.[i]?.signedUrl;if(url)urls.set(r.ping_id,url);});}const last=new Map<string,string|null>();(meta.data||[]).forEach(r=>last.set(String((r as MetaRow).id),(r as MetaRow).last_confirmed_at));return rows.map(r=>({...r,mediaUrl:urls.get(r.id),lastConfirmedAt:last.get(r.id)||null}));}

export default function SearchPage(){
  const router=useRouter();
  const[query,setQuery]=useState("");const[debouncedQuery,setDebouncedQuery]=useState("");const[category,setCategory]=useState<CategoryKey>("all");const[radius,setRadius]=useState<Radius>(1);const[sort,setSort]=useState<SortKey>("best");const[coordinates,setCoordinates]=useState<PingCoordinates|null>(null);const[locationState,setLocationState]=useState<PingLocationState>("checking");const[items,setItems]=useState<SearchItem[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[refreshNonce,setRefreshNonce]=useState(0);
  useEffect(()=>{setRadius(readPingRadius());let cancelled=false;void getPingLocationSilently().then(result=>{if(cancelled)return;setLocationState(result.state);if(result.coordinates)setCoordinates(result.coordinates);});return()=>{cancelled=true;};},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQuery(query.trim()),260);return()=>window.clearTimeout(timer);},[query]);
  const requestLocation=async()=>{setLocationState("requesting");const result=await requestPingLocation();setLocationState(result.state);if(result.coordinates)setCoordinates(result.coordinates);};
  useEffect(()=>{if(!coordinates)return;let cancelled=false;const load=async()=>{setLoading(true);setError("");try{const{data,error:rpcError}=await createClient().rpc("search_nearby_pings",{viewer_lat:coordinates.lat,viewer_lng:coordinates.lng,search_query:debouncedQuery,category_filter:category==="all"?null:category,radius_meters:Math.round(radius*1609.344),result_limit:60});if(rpcError)throw rpcError;const next=await enrich((data||[])as SearchRow[]);if(!cancelled)setItems(next);}catch(e){console.error("Search failed",e);if(!cancelled){setItems([]);setError("Nearby search is temporarily unavailable.");}}finally{if(!cancelled)setLoading(false);}};void load();return()=>{cancelled=true;};},[coordinates,debouncedQuery,category,radius,refreshNonce]);
  useEffect(()=>{if(!coordinates)return;const supabase=createClient();const channel=supabase.channel("search-live-v3").on("postgres_changes",{event:"*",schema:"public",table:"pings"},()=>setRefreshNonce(v=>v+1)).subscribe();return()=>{void supabase.removeChannel(channel);};},[coordinates]);
  const sorted=useMemo(()=>{const next=[...items];if(sort==="newest")next.sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());if(sort==="closest")next.sort((a,b)=>a.distance_meters-b.distance_meters);if(sort==="confirmed")next.sort((a,b)=>b.confirmation_count-a.confirmation_count||new Date(b.created_at).getTime()-new Date(a.created_at).getTime());if(sort==="best"&&debouncedQuery)next.sort((a,b)=>b.search_rank-a.search_rank||b.confirmation_count-a.confirmation_count);return next;},[items,sort,debouncedQuery]);
  const setAndStoreRadius=(next:Radius)=>{setRadius(next);writePingRadius(next);};
  const openPing=(item:SearchItem)=>{const meta=CATEGORY_DEFINITIONS[item.category];window.dispatchEvent(new CustomEvent("ping:open-detail",{detail:{id:item.id,title:item.title,body:item.body,category:meta.label,place:item.place_label||"Nearby",distanceMiles:item.distance_meters/1609.344,confirmations:item.confirmation_count,live:true}}));};
  const discoverMode=!debouncedQuery;
  return <div className="search-v3-page"><div className="search-v3-shell">
    <header className="search-v3-head"><button type="button" onClick={()=>router.push("/")} aria-label="Back to Feed"><PingIcon name="chevron" size={18} style={{transform:"rotate(180deg)"}}/></button><div><div className="brand small">pindrizzle</div><p>Search & discover</p></div><button type="button" onClick={()=>router.push("/map")} aria-label="Open Map"><PingIcon name="map" size={18}/></button></header>
    <section className="search-v3-intro"><h1>{discoverMode?"Find what matters nearby":"Search your area"}</h1><p>{discoverMode?"Deals, outages, traffic, Marketplace and useful local pins — never a global feed.":`Active matches inside ${radius} ${radius===1?"mile":"miles"}.`}</p></section>
    <div className="search-v3-searchbox"><PingIcon name="search" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “road closed”, “deal”, “room”…" maxLength={120} aria-label="Search nearby pins"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Clear search"><PingIcon name="plus" size={14} style={{transform:"rotate(45deg)"}}/></button>}</div>
    <div className="search-v3-chips" aria-label="Search categories"><button type="button" className={category==="all"?"active":""} onClick={()=>setCategory("all")}>All</button>{CATEGORY_ORDER.map(key=>{const meta=CATEGORY_DEFINITIONS[key];return <button key={key} type="button" className={category===key?"active":""} onClick={()=>setCategory(key)}><PingIcon name={meta.icon} size={14}/>{meta.shortLabel}</button>;})}</div>
    <div className="search-v3-controls"><label><span>Radius</span><select value={radius} onChange={e=>setAndStoreRadius(Number(e.target.value)as Radius)}><option value={0.5}>0.5 mi</option><option value={1}>1 mi</option><option value={3}>3 mi</option><option value={5}>5 mi</option></select></label><label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value as SortKey)}><option value="best">{debouncedQuery?"Best match":"Recommended"}</option><option value="newest">Newest</option><option value="closest">Closest</option><option value="confirmed">Most confirmed</option></select></label></div>
    {locationState!=="granted"&&<section className="search-v3-location"><span><PingIcon name="location" size={20}/></span><div><strong>{locationState==="denied"?"Location is blocked":"Search starts with your location"}</strong><p>{locationState==="denied"?"Enable location in your device settings, then try again.":"Search reuses the same Pindrizzle location permission as Feed and Map."}</p></div><button type="button" onClick={()=>void requestLocation()} disabled={locationState==="requesting"||locationState==="checking"}>{locationState==="requesting"||locationState==="checking"?"Checking…":"Use location"}</button></section>}
    {locationState==="granted"&&<div className="search-v3-status"><span/><strong>{loading?"Searching nearby…":`${sorted.length} active ${sorted.length===1?"pin":"pins"}`}</strong><small>{debouncedQuery?`matching “${debouncedQuery}”`:"available to discover"}</small></div>}
    <main className="search-v3-results">{error&&<div className="search-v3-empty pd-moment"><span><PingIcon name="search" size={26}/></span><h2>Search couldn’t load</h2><p>{error}</p></div>}{!error&&coordinates&&!loading&&sorted.length===0&&<div className="search-v3-empty pd-moment"><span><PingIcon name="search" size={26}/></span><h2>{debouncedQuery?"No nearby matches":"Quiet around here"}</h2><p>{debouncedQuery?"Try fewer words, another category, or a wider radius.":"There are no active pins in this area right now."}</p></div>}{!error&&sorted.map(item=>{const meta=CATEGORY_DEFINITIONS[item.category];return <article key={item.id} className="search-v3-card" onClick={()=>openPing(item)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openPing(item);}}}><div className="search-v3-cardtop"><span><PingIcon name={meta.icon} size={14}/>{meta.label}</span><b>{ageLabel(item.created_at)}</b></div><h2 data-user-content>{item.title}</h2><p data-user-content>{item.body}</p>{item.mediaUrl&&<img src={item.mediaUrl} alt={`Photo attached to ${item.title}`} loading="lazy"/>}<div className="search-v3-meta"><span><PingIcon name="location" size={13}/>{(item.distance_meters/1609.344).toFixed(1)} mi</span><span><PingIcon name="confirmations" size={13}/>{item.confirmation_count} confirmed{item.lastConfirmedAt?` · ${confirmLabel(item.lastConfirmedAt)}`:""}</span><span><PingIcon name="replies" size={13}/>{item.comment_count}</span></div></article>;})}</main>
  </div><style jsx global>{`
    .search-v3-page{height:100dvh;min-height:100svh;max-height:100dvh;overflow:hidden;background:var(--pd-canvas);color:var(--pd-text)}
    .search-v3-shell{width:100%;height:100%;overflow-x:hidden;overflow-y:auto;overscroll-behavior-y:contain;-webkit-overflow-scrolling:touch;padding:calc(var(--pd-safe-top) + var(--pd-space-2)) max(var(--pd-space-3),var(--pd-safe-right)) calc(var(--pd-tabbar-total) + var(--pd-space-3)) max(var(--pd-space-3),var(--pd-safe-left))}
    .search-v3-head{display:grid;grid-template-columns:44px 1fr 44px;gap:var(--pd-space-2);align-items:center;padding:var(--pd-space-2) 0 var(--pd-space-3)}.search-v3-head>div{text-align:center}.search-v3-head .brand{align-items:center!important}.search-v3-head p{margin:var(--pd-space-1) 0 0;color:var(--pd-muted);font-size:9px}.search-v3-head>button{width:44px;height:44px;border:1px solid var(--pd-line);border-radius:var(--pd-radius-pill);background:rgba(255,255,255,.82);color:var(--pd-ink-800);display:grid;place-items:center;box-shadow:none}
    .search-v3-intro{padding:var(--pd-space-3) 0 var(--pd-space-2);text-align:left}.search-v3-intro h1{font-size:29px;line-height:1.05;letter-spacing:-.04em;margin:0 0 var(--pd-space-2);color:var(--pd-ink-950)}.search-v3-intro p{margin:0;color:var(--pd-muted);font-size:12px;line-height:1.5}
    .search-v3-searchbox{margin:var(--pd-space-2) 0 var(--pd-space-3);background:rgba(255,255,255,.94);border:1px solid var(--pd-line);border-radius:var(--pd-radius-control);height:52px;display:grid;grid-template-columns:40px 1fr 40px;align-items:center;padding:0 var(--pd-space-1);box-shadow:var(--pd-elevation-1)}.search-v3-searchbox>svg{margin:auto;color:var(--pd-ink-800)}.search-v3-searchbox input{border:0!important;outline:0;background:transparent!important;width:100%;font-size:14px;color:var(--pd-text);box-shadow:none!important}.search-v3-searchbox button{border:0;background:var(--pd-silver-100);color:var(--pd-ink-800);border-radius:50%;width:32px;height:32px;display:grid;place-items:center;margin:auto}
    .search-v3-chips{display:flex;gap:var(--pd-space-2);overflow:auto;padding:0 0 var(--pd-space-3);scrollbar-width:none;overscroll-behavior:none}.search-v3-chips::-webkit-scrollbar{display:none}.search-v3-chips button{flex:0 0 auto;min-height:44px;display:flex;align-items:center;gap:6px;border:1px solid var(--pd-line);background:rgba(255,255,255,.82);border-radius:var(--pd-radius-pill);padding:0 14px;color:var(--pd-text-2);font-size:9px;font-weight:720}.search-v3-chips button.active{background:var(--pd-ink-900);color:#fff;border-color:var(--pd-ink-900)}
    .search-v3-controls{display:grid;grid-template-columns:1fr 1fr;gap:var(--pd-space-2);padding-bottom:var(--pd-space-3)}.search-v3-controls label{min-height:44px;background:var(--pd-silver-100);border:1px solid var(--pd-line);border-radius:var(--pd-radius-control);padding:8px 10px;display:grid;grid-template-columns:1fr auto;align-items:center}.search-v3-controls span{font-size:8px;color:var(--pd-muted);font-weight:800;text-transform:uppercase}.search-v3-controls select{min-height:32px;border:0!important;background:transparent!important;color:var(--pd-text-2);font-size:10px;font-weight:750;box-shadow:none!important}
    .search-v3-location{padding:var(--pd-space-3);border:1px solid rgba(37,189,200,.18);border-radius:var(--pd-radius-card);background:linear-gradient(135deg,var(--pd-aqua-100),rgba(255,255,255,.92));display:grid;grid-template-columns:40px 1fr auto;gap:var(--pd-space-2);align-items:center;box-shadow:var(--pd-elevation-1)}.search-v3-location>span{width:40px;height:40px;display:grid;place-items:center;border-radius:12px;background:#fff;color:#0c7187}.search-v3-location strong{font-size:11px}.search-v3-location p{margin:3px 0 0;color:var(--pd-muted);font-size:9px;line-height:1.4}.search-v3-location button{min-height:44px;border:1px solid var(--pd-ink-900);background:var(--pd-ink-900);color:#fff;border-radius:var(--pd-radius-pill);padding:0 14px;font-size:9px;font-weight:760}
    .search-v3-status{padding:var(--pd-space-2) 2px var(--pd-space-3);display:flex;align-items:center;gap:7px;color:var(--pd-text-2)}.search-v3-status>span{width:7px;height:7px;border-radius:50%;background:var(--pd-aqua-500)}.search-v3-status strong{font-size:10px}.search-v3-status small{font-size:8px;color:var(--pd-muted);margin-left:auto}
    .search-v3-results{display:grid;gap:var(--pd-space-2)}.search-v3-card{background:rgba(255,255,255,.94);border:1px solid var(--pd-line);border-radius:var(--pd-radius-card);padding:var(--pd-space-3);cursor:pointer;box-shadow:var(--pd-elevation-1);text-align:left}.search-v3-card:focus-visible{outline:3px solid rgba(37,189,200,.24);outline-offset:2px}.search-v3-cardtop{display:flex;justify-content:space-between;align-items:center}.search-v3-cardtop span{display:inline-flex;align-items:center;gap:6px;font-size:9px;font-weight:750;color:var(--pd-text-2)}.search-v3-cardtop b{color:var(--pd-muted);font-size:8px}.search-v3-card h2{font-size:17px;line-height:1.2;margin:var(--pd-space-2) 0 7px;color:var(--pd-ink-950)}.search-v3-card>p{font-size:11px;line-height:1.5;color:var(--pd-muted);margin:0 0 var(--pd-space-2);display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.search-v3-card>img{width:100%;max-height:220px;object-fit:cover;border-radius:14px;margin:0 0 var(--pd-space-2)}.search-v3-meta{display:flex;flex-wrap:wrap;gap:8px 12px;padding-top:var(--pd-space-2);border-top:1px solid var(--pd-line);color:var(--pd-muted);font-size:8px}.search-v3-meta span{display:flex;align-items:center;gap:4px}
    .search-v3-empty{display:grid;justify-items:center;gap:var(--pd-space-2);text-align:center;background:rgba(255,255,255,.94);border:1px solid var(--pd-line);border-radius:var(--pd-radius-card);padding:var(--pd-space-5) var(--pd-space-4);box-shadow:var(--pd-elevation-1)}.search-v3-empty>span{width:52px;height:52px;display:grid;place-items:center;border-radius:16px;background:var(--pd-aqua-100);color:#0c7187}.search-v3-empty h2{font-size:17px;margin:0;color:var(--pd-ink-950)}.search-v3-empty p{font-size:11px;color:var(--pd-muted);line-height:1.5;margin:0;max-width:300px}
    @media(max-width:350px){.search-v3-location{grid-template-columns:40px 1fr}.search-v3-location button{grid-column:1/-1;width:100%}}
  `}</style></div>;
}
